{{ if .Values.waitForMetalNode }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.vms.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
{{ end }}
