---
global:
  pattern: ansible-edge-gitops

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

vmNamespace: edge-gitops-vms

waitForMetalNode: true
jobTerminationGracePeriod: 3600

vmDefaults:
  cloudInitSecret: secret/data/hub/cloud-init
  accessMode: "ReadWriteMany"
  storageClassName: "ocs-storagecluster-ceph-rbd-virtualization"
  volumeMode: "Block"
  count: 1
  flavor: medium
  workload: desktop
  os: rhel8
  storage: 30Gi
  memory: 4Gi
  machineType: pc-q35-rhel8.4.0
  cores: 1
  sockets: 1
  threads: 1
  template: rhel8-desktop-medium
  sshsecret: secret/data/hub/vm-ssh
  cloudinitsecret: secret/data/hub/cloud-init
  sshpubkeyfield: publickey
  # extraLabels is available for default extra labels to add to the virtualmachine
  # extraAnnotations is available for default extra labels to add to the virtualmachine
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22

# Define the VMs you want to create with any specific attributes from vmDefaults
# in an overrides file.
vms: {}

serviceAccountName: ansible-edge-gitops-sa
rbac:
  roles:
    - name: view-machine-api
      createRole: true
      apiGroups:
        - machine.openshift.io
      scope:
        cluster: true
      resources:
        - machinesets
      verbs:
        - "get"
        - "list"
        - "watch"
  roleBindings:
    - name: view-machine-api
      createBinding: true
      scope:
        cluster: false
        namespace: "openshift-machine-api"
      subjects:
        kind: ServiceAccount
        name: ansible-edge-gitops-sa
        namespace: edge-gitops-vms
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: view-machine-api

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
